// SPDX-License-Identifier: AGPL-3.0-or-later
const IT={
  'Home':'Home','Ask · Create · Act':'Chiedi · Crea · Agisci','Projects':'Progetti','Tasks':'Attività','Artifacts':'Artefatti','Agents & Tools':'Agenti e strumenti','Knowledge':'Conoscenza','Memory':'Memoria','Models & APIs':'Modelli e API','Compute':'Risorse di calcolo',
  'Ask':'Chiedi','Create':'Crea','Act':'Agisci','Project':'Progetto','Conversation':'Conversazione','Branch':'Ramo','Provider / route':'Provider / instradamento','Model':'Modello','Compare models':'Confronta modelli','Compare branches':'Confronta rami','Merge':'Unisci','Fork':'Ramifica','Context':'Contesto','Undo':'Annulla','Stop':'Interrompi','Send':'Invia',
  'Create project':'Crea progetto','Available projects':'Progetti disponibili','New task':'Nuova attività','Work queue':'Coda di lavoro','New artifact':'Nuovo artefatto','Add source':'Aggiungi fonte','Search':'Cerca','Add memory':'Aggiungi memoria','Visible memory':'Memoria visibile','Add provider':'Aggiungi provider','Provider profiles':'Profili provider','Register tool':'Registra strumento','Create agent':'Crea agente','Plan run':'Pianifica esecuzione','Installed tools':'Strumenti installati','Runs':'Esecuzioni',
  'Name':'Nome','Description':'Descrizione','Project instructions':'Istruzioni progetto','Tags':'Etichette','Priority':'Priorità','Schedule':'Programmazione','Due':'Scadenza','Status':'Stato','Title':'Titolo','Content':'Contenuto','Type':'Tipo','Scope':'Ambito','Base URL':'URL di base','Default model':'Modello predefinito','Routing priority':'Priorità instradamento','Modes':'Modalità','Transport':'Trasporto','Endpoint or executable':'Endpoint o eseguibile','Remote tool name':'Nome strumento remoto','Goal':'Obiettivo','Tools':'Strumenti','Instructions':'Istruzioni',
  'Export workspace':'Esporta workspace','Delete active project data':'Elimina dati progetto attivo','Ready':'Pronto','Automatic route':'Instradamento automatico','No projects.':'Nessun progetto.','No tasks.':'Nessuna attività.','No artifacts.':'Nessun artefatto.','No memory.':'Nessuna memoria.','No sources.':'Nessuna fonte.','No tools.':'Nessuno strumento.','No runs.':'Nessuna esecuzione.'
};
const dictionaries={en:{},it:IT};
let current='en';
function language(){const stored=localStorage.getItem('noesar-language')||'auto';if(stored!=='auto')return stored;return navigator.language.toLowerCase().startsWith('it')?'it':'en';}
function translateNode(node,dict){if(node.nodeType===Node.TEXT_NODE){const raw=node.nodeValue;const trimmed=raw.trim();if(trimmed&&dict[trimmed])node.nodeValue=raw.replace(trimmed,dict[trimmed]);return;}if(node.nodeType!==Node.ELEMENT_NODE||['SCRIPT','STYLE','CODE','PRE'].includes(node.tagName))return;for(const child of node.childNodes)translateNode(child,dict);for(const attr of ['placeholder','title','aria-label']){const value=node.getAttribute?.(attr);if(value&&dict[value])node.setAttribute(attr,dict[value]);}}
export function applyTranslations(){current=language();document.documentElement.lang=current;const dict=dictionaries[current]??{};translateNode(document.body,dict);const select=document.querySelector('#languageSelect');if(select)select.value=localStorage.getItem('noesar-language')||'auto';}
export function initI18n(){applyTranslations();document.querySelector('#languageSelect')?.addEventListener('change',(event)=>{localStorage.setItem('noesar-language',event.target.value);location.reload();});return current;}
