// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SESS-002/SESS-003 (MASTER_PROJECT/01_VISIONE_E_POSIZIONE.md): the replay engine. Two
// distinct questions, one shared idea — recompute the decision layer against the SAME inputs
// and compare, rather than trust what was recorded.
//
// compareDecisions() is deliberately dumb: a structural comparison of the fields the decision
// layer produces. All the actual semantics live in ReferenceReasoningProvider / ReasoningRouter
// (workspace-actions.mjs's own #runDecisionLayer calls them); a SECOND comparison here that
// re-derived what "the same" means would be exactly the "two implementations of one rule stop
// agreeing" failure this project keeps finding and removing (11_REVISIONE_E_CORREZIONI.md, and
// D-0227's own comment about not re-implementing the provider's comparison logic).
//
// callAtomReplay() is a thin, injectable client for atomd's `/v1/replay` — an ATOM EXTENSION,
// not one of the twelve frozen ReasoningProvider surfaces (atom-client.mjs's own comment says
// so, and refuses to route it), so it is not sent through AtomClient. This is the same protocol
// `tools/measure-replay-fidelity.mjs` already proved faithful (D-0227, FAITHFUL_SESSIONS=8/8,
// oracle proven for tampering) — made reachable from the product itself, not only from a
// standalone instrument.

import { ReasoningUnavailable } from './atom-client.mjs';

const DECISION_FIELDS = Object.freeze(['intent', 'hypotheses', 'plan', 'risk', 'confidence', 'expectation']);
const DEFAULT_TIMEOUT_MS = 10_000;

/**
 * The reasoning surfaces `#runDecisionLayer` actually calls to PRODUCE a decision. `fixtures`
 * is deliberately excluded: it is the capture mechanism, not a decision surface — a run that
 * routed only `fixtures` externally (capture failed or not) had every decision-relevant
 * surface answered locally, and its decision layer is exactly as recomputable as a run that
 * used no external provider at all. Checking provenance for ANY `atom` entry, `fixtures`
 * included, would send a fully-local decision down the EXTERNAL_PACK path for no reason.
 */
export const DECISION_SURFACES = Object.freeze([
  'interpret', 'hypothesize', 'constrain', 'classify', 'confidence', 'expect',
]);

/**
 * Structural comparison of the fields the decision layer produces. Order-sensitive on
 * purpose — a plan whose steps reordered is a different plan, not the same one restated.
 */
export function compareDecisions(original, recomputed) {
  const diffs = [];
  for (const field of DECISION_FIELDS) {
    const was = JSON.stringify(original[field] ?? null);
    const now = JSON.stringify(recomputed[field] ?? null);
    if (was !== now) diffs.push({ field, was: original[field] ?? null, now: recomputed[field] ?? null });
  }
  return { faithful: diffs.length === 0, diffs };
}

/** POSTs a captured fixture pack to atomd's `/v1/replay` and returns its own report. */
export async function callAtomReplay({ endpoint, token, pack, fetchImpl = fetch, timeoutMs = DEFAULT_TIMEOUT_MS }) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  let response;
  try {
    response = await fetchImpl(`${endpoint}/v1/replay`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-atom-token': token ?? '' },
      body: JSON.stringify({ pack }),
      signal: controller.signal,
    });
  } catch (error) {
    throw new ReasoningUnavailable(
      `the external provider at ${endpoint} could not be reached for replay: ${error?.message ?? error}`,
      { surface: 'replay', endpoint },
    );
  } finally {
    clearTimeout(timer);
  }
  let envelope;
  try {
    envelope = JSON.parse(await response.text());
  } catch {
    throw new ReasoningUnavailable(
      `the external provider answered replay ${response.status} with something that is not JSON`,
      { surface: 'replay', endpoint },
    );
  }
  if (envelope?.ok !== true || !('value' in envelope)) {
    const reason = envelope?.error?.reason ?? `http ${response.status}`;
    throw new ReasoningUnavailable(`replay refused: ${reason}`, { surface: 'replay', endpoint });
  }
  return envelope.value;
}

/**
 * SESS-003: does the product's OWN decision code, as it exists right now, still reach the
 * same constrain/classify verdict a historical fixture recorded? Deliberately independent of
 * which external provider (if any) answered at record time — SESS-003 is about the product's
 * code changing across versions, not about a model's answer changing, which SESS-002 already
 * covers honestly (`EXTERNAL_PACK`, replayed through the SAME provider that answered
 * originally, never regenerated by a different one).
 */
export function comparePolicyOutcome(historical, current) {
  const was = { refused: Boolean(historical.refused), riskOverall: historical.riskOverall ?? null };
  const now = { refused: Boolean(current.refused), riskOverall: current.riskOverall ?? null };
  const changed = was.refused !== now.refused || was.riskOverall !== now.riskOverall;
  return { changed, was, now };
}
