// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Generates the eight alternative themes as token remappings, from the default theme.
//
// Why generated rather than hand-written: a theme is 60-odd token values, and hand-writing
// them is how a theme ends up with one surface that stayed dark and one label nobody can
// read. The generator preserves the ORDER of the default theme — which surface is deeper
// than which, which text is quieter than which — and only moves the scheme. The visual
// hierarchy the interface was designed with therefore survives a change of theme, instead
// of being re-invented eight times.
//
// It is committed and re-runnable so the themes can be regenerated when a token is added,
// rather than drifting from the default one edit at a time.
//
// What it does NOT do is decide whether a theme is readable. That is measured afterwards by
// tools/accessibility-audit.mjs, which now walks every theme. Generation is a proposal;
// the audit is the verdict.
//
//   node tools/generate-themes.mjs           rewrite the theme blocks in styles.css
//   node tools/generate-themes.mjs --check    fail if they are out of date
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parseHex, toHex, rgbToHsl, hslToRgb, deriveReadable } from '../apps/webui-static/colour.js';

const here = dirname(fileURLToPath(import.meta.url));
const CSS = join(here, '../apps/webui-static/styles.css');
const BEGIN = '/* THEMES:BEGIN — generated by tools/generate-themes.mjs, do not edit by hand */';
const END = '/* THEMES:END */';

// The nine themes. The default carries no block: it IS the token values in :root, so it
// cannot drift from them.
const THEMES = [
  { id: 'midnight', label: 'Midnight', scheme: 'dark', accent: null, note: 'the default' },
  { id: 'slate', label: 'Slate', scheme: 'dark', accent: 205, neutral: 210 },
  { id: 'graphite', label: 'Graphite', scheme: 'dark', accent: 220, neutral: 30, neutralSaturation: 0.06 },
  { id: 'indigo', label: 'Indigo', scheme: 'dark', accent: 228 },
  { id: 'teal', label: 'Teal', scheme: 'dark', accent: 186 },
  { id: 'amber', label: 'Amber', scheme: 'dark', accent: 38 },
  { id: 'violet', label: 'Violet', scheme: 'dark', accent: 268 },
  { id: 'daylight', label: 'Daylight', scheme: 'light', accent: null },
  { id: 'contrast', label: 'High contrast', scheme: 'contrast', accent: null },
];

// --- reading the default theme ---------------------------------------------
function readTokens(css) {
  const root = /:root\{([\s\S]*?)\n\}/.exec(css);
  if (!root) throw new Error(':root block not found');
  const tokens = new Map();
  for (const match of root[1].matchAll(/--([a-z0-9-]+)\s*:\s*([^;]+);/g)) {
    tokens.set(match[1], match[2].trim());
  }
  return tokens;
}
function parseValue(value) {
  const hex = parseHex(value);
  if (hex) return { rgb: hex, alpha: 1, form: 'hex' };
  const rgba = /rgba?\(([^)]+)\)/.exec(value);
  if (!rgba) return null;
  const parts = rgba[1].split(/[\s,/]+/).filter(Boolean).map(Number);
  if (parts.length < 3 || parts.some(Number.isNaN)) return null;
  return { rgb: { r: parts[0], g: parts[1], b: parts[2] }, alpha: parts.length > 3 ? parts[3] : 1, form: 'rgb' };
}
function emit({ rgb, alpha, form }) {
  if (form === 'hex' && alpha === 1) return toHex(rgb);
  const round = (n) => Math.max(0, Math.min(255, Math.round(n)));
  return `rgba(${round(rgb.r)},${round(rgb.g)},${round(rgb.b)},${alpha})`;
}

// Which family a token belongs to. The names were chosen in the token layer for exactly
// this: the theme layer can act on a whole family without listing its members.
function familyOf(name) {
  if (/^(surface-|panel|panel2|scrim)/.test(name)) return 'surface';
  if (/^(text-|muted)/.test(name)) return 'text';
  if (/^accent-/.test(name)) return 'accent';
  if (/^(state-|blue|cyan|green|amber|red)$|^state-/.test(name)) return 'state';
  if (/^(border-|line|focus-ring)/.test(name)) return 'border';
  if (/^(shadow-|glow-)/.test(name)) return 'effect';
  return 'other';
}

// --- the transformations ----------------------------------------------------
// Rank-preserving: a token's position in its family's lightness order is kept, and only the
// range that order is drawn from changes. That is what stops a generated theme from
// flattening the interface into one shade.
function rankMap(names, tokens, familyFilter) {
  const members = names.filter((n) => familyOf(n) === familyFilter);
  const withLightness = members.map((name) => {
    const parsed = parseValue(tokens.get(name));
    return { name, parsed, l: parsed ? rgbToHsl(parsed.rgb).l : 0 };
  }).filter((entry) => entry.parsed);
  const sorted = [...withLightness].sort((a, b) => a.l - b.l);
  const positions = new Map();
  sorted.forEach((entry, index) => {
    positions.set(entry.name, sorted.length === 1 ? 0.5 : index / (sorted.length - 1));
  });
  return { members: withLightness, positions };
}
function lerp(from, to, t) { return from + (to - from) * t; }

function buildTheme(theme, tokens) {
  const names = [...tokens.keys()];
  const out = new Map();
  const surfaces = rankMap(names, tokens, 'surface');
  const texts = rankMap(names, tokens, 'text');
  const borders = rankMap(names, tokens, 'border');
  const effects = rankMap(names, tokens, 'effect');

  // The background a theme's text is judged against: its deepest surface for dark schemes,
  // its lightest for light ones. Used for the semantic-state derivation below.
  let pageBackground;

  const set = (name, parsed) => out.set(name, emit(parsed));
  const recolour = (name, { l, h, s }) => {
    const parsed = parseValue(tokens.get(name));
    if (!parsed) return;
    const hsl = rgbToHsl(parsed.rgb);
    const next = hslToRgb({
      h: h === undefined ? hsl.h : h,
      s: s === undefined ? hsl.s : s,
      l: l === undefined ? hsl.l : l,
    });
    set(name, { rgb: next, alpha: parsed.alpha, form: parsed.form });
  };

  if (theme.scheme === 'light') {
    // Surfaces climb to white; the deepest surface of the dark theme becomes the lightest
    // paper, so panels still read as raised against the page.
    for (const { name } of surfaces.members) {
      recolour(name, { l: lerp(0.99, 0.90, surfaces.positions.get(name)), s: 0.16 });
    }
    // Text descends into near-black keeping its PROMINENCE order, which means the rank is
    // INVERTED here: the lightest token of a dark theme is its loudest text, so it must
    // become the darkest one now. Mapping lightness straight to lightness turned the
    // hierarchy upside down and put headings at 1.2:1 on white. Found by measuring nine
    // themes, not by reading the generator.
    for (const { name } of texts.members) {
      if (name === 'text-on-accent') continue; // this one still sits on a saturated fill
      recolour(name, { l: lerp(0.38, 0.10, texts.positions.get(name)), s: 0.18 });
    }
    for (const { name } of borders.members) {
      if (name === 'focus-ring') { recolour(name, { l: 0.34, s: 0.85 }); continue; }
      recolour(name, { l: lerp(0.62, 0.78, borders.positions.get(name)), s: 0.22 });
    }
    for (const { name } of effects.members) {
      const parsed = parseValue(tokens.get(name));
      set(name, { rgb: { r: 15, g: 23, b: 42 }, alpha: Math.min(parsed.alpha, 0.18), form: 'rgb' });
    }
    pageBackground = '#fdfdfe';
  } else if (theme.scheme === 'contrast') {
    // Not "a bit darker": black behind, white in front, every border visible. A high
    // contrast theme that merely deepens the palette is the one users switch on and find
    // has changed nothing.
    for (const { name } of surfaces.members) {
      recolour(name, { l: lerp(0.0, 0.10, surfaces.positions.get(name)), s: 0.0 });
    }
    for (const { name } of texts.members) {
      if (name === 'text-on-accent') continue;
      recolour(name, { l: lerp(0.88, 1.0, texts.positions.get(name)), s: 0.0 });
    }
    for (const { name } of borders.members) {
      recolour(name, { l: name === 'focus-ring' ? 1 : 0.82, s: name === 'focus-ring' ? 0 : 0.1 });
    }
    for (const { name } of effects.members) {
      set(name, { rgb: { r: 0, g: 0, b: 0 }, alpha: 0, form: 'rgb' });
    }
    pageBackground = '#000000';
  } else {
    // The WORST realistic backdrop, not the best one. `surface-root` is the deepest colour
    // in the theme, so deriving a state colour against it flatters every measurement: the
    // real page shows lighter panels and a radial glow behind them, and a state derived to
    // exactly 4.5:1 on the deepest surface lands at 4.2:1 on the lightest. Fills and the
    // inverse surface are excluded — they carry their own text and are not a page backdrop.
    const backdrops = names.filter((n) => familyOf(n) === 'surface' && !/inverse|avatar|selected/.test(n))
      .map((n) => ({ n, parsed: parseValue(tokens.get(n)) }))
      .filter((entry) => entry.parsed && entry.parsed.alpha === 1 && rgbToHsl(entry.parsed.rgb).l < 0.5)
      .sort((a, b) => rgbToHsl(b.parsed.rgb).l - rgbToHsl(a.parsed.rgb).l);
    pageBackground = backdrops.length ? toHex(backdrops[0].parsed.rgb) : tokens.get('surface-root');
    if (theme.neutral !== undefined) {
      for (const family of ['surface', 'text', 'border']) {
        for (const name of names.filter((n) => familyOf(n) === family)) {
          const parsed = parseValue(tokens.get(name));
          if (!parsed) continue;
          const hsl = rgbToHsl(parsed.rgb);
          if (hsl.s < 0.02) continue; // a true grey stays grey
          recolour(name, { h: theme.neutral / 360, s: theme.neutralSaturation ?? hsl.s });
        }
      }
    }
  }

  // The accent, for every theme that names one. This is the family the free colour picker
  // moves too, which is why it is a family and not a single value.
  if (theme.accent !== null && theme.accent !== undefined) {
    for (const name of names.filter((n) => familyOf(n) === 'accent')) {
      recolour(name, { h: theme.accent / 360 });
    }
    recolour('blue', { h: theme.accent / 360 });
  }
  if (theme.scheme === 'light' || theme.scheme === 'contrast') {
    for (const name of names.filter((n) => familyOf(n) === 'accent')) {
      const parsed = parseValue(tokens.get(name));
      if (!parsed) continue;
      const hsl = rgbToHsl(parsed.rgb);
      const target = theme.scheme === 'contrast' ? 0.62 : Math.min(hsl.l, 0.42);
      recolour(name, { l: target, s: theme.scheme === 'contrast' ? Math.max(hsl.s, 0.75) : hsl.s });
    }
  }

  // Accent FILLS carry white text, so rotating a hue is not enough: the same lightness
  // that reads at indigo is far too bright at teal or amber, and white on it drops to
  // 1.9:1. Each fill is derived away from the colour written on it until the pairing
  // carries. The audit found this by measuring nine themes; rotating the hue and looking at
  // the result would not have.
  const FILL_TOKENS = ['accent-fill-from', 'accent-fill-to', 'surface-avatar-from', 'surface-avatar-to', 'surface-selected'];
  // The text on a fill is not always pure white: the brand mark and the avatar inherit
  // --text-primary, which is darker, and a fill derived to 4.6:1 against white lands at
  // 4.3:1 against it. Derive against the DARKER of the two, with margin.
  const textCandidates = ['text-on-accent']
    .map((name) => out.get(name) ?? tokens.get(name)).filter(Boolean)
    .map((value) => parseValue(value)).filter(Boolean);
  const textOnFill = textCandidates.sort((a, b) => rgbToHsl(a.rgb).l - rgbToHsl(b.rgb).l)[0];
  for (const name of FILL_TOKENS) {
    const value = out.get(name) ?? tokens.get(name);
    const parsed = parseValue(value);
    if (!parsed || parsed.alpha < 1) continue;
    const derived = deriveReadable(toHex(parsed.rgb), toHex(textOnFill.rgb), 5.0);
    if (derived) out.set(name, derived.hex);
  }

  // Accent TEXT — links, the eyebrow, the brand word — is read against the page, not
  // against a fill, so it needs the same derivation the states get. Rotating a hue and
  // clamping its lightness left two of them at 4.4:1 in the high-contrast theme, which is
  // the one theme where that is least forgivable.
  for (const name of ['accent-link', 'accent-brand', 'accent-eyebrow']) {
    const value = out.get(name) ?? tokens.get(name);
    const parsed = parseValue(value);
    if (!parsed || parsed.alpha < 1) continue;
    const derived = deriveReadable(toHex(parsed.rgb), pageBackground, theme.scheme === 'dark' ? 5.0 : 6.0);
    if (derived) out.set(name, derived.hex);
  }

  // UI-026: the semantic states may move in LIGHTNESS to stay legible. Never in hue, so the
  // meaning and the glyph they travel with are untouched. The new lightness is not guessed:
  // it is derived until the text carries against this theme's page background.
  for (const name of names.filter((n) => familyOf(n) === 'state')) {
    const value = out.get(name) ?? tokens.get(name);
    const parsed = parseValue(value);
    if (!parsed || parsed.alpha < 1) continue;
    // Margin on the schemes that were rebuilt from scratch: a state colour is judged
    // against whatever backdrop resolves as worst case, which is not always the page
    // background it was derived against.
    const derived = deriveReadable(toHex(parsed.rgb), pageBackground, theme.scheme === 'dark' ? 4.5 : 6.0);
    if (derived && derived.hex !== toHex(parsed.rgb)) {
      out.set(name, derived.hex);
    }
  }
  return out;
}

// --- rendering --------------------------------------------------------------
const css = readFileSync(CSS, 'utf8');
const tokens = readTokens(css);
const blocks = [];
blocks.push('/* Nine themes, and each is a REMAPPING of the tokens above — never a second');
blocks.push('   stylesheet. `midnight` has no block: it is the token values themselves, so it');
blocks.push('   cannot drift from them. UI-020, UI-021, UI-026. */');
for (const theme of THEMES) {
  if (theme.id === 'midnight') continue;
  const values = buildTheme(theme, tokens);
  const lines = [...values.entries()].sort(([a], [b]) => (a < b ? -1 : 1)).map(([name, value]) => `  --${name}:${value};`);
  blocks.push(`:root[data-theme="${theme.id}"]{`);
  blocks.push(lines.join('\n'));
  blocks.push('}');
}
// A theme must also tell the browser which scheme it is, or form controls and scrollbars
// keep rendering for the old one.
blocks.push(':root[data-theme="daylight"]{color-scheme:light}');
blocks.push(':root[data-theme="contrast"]{color-scheme:dark}');

const generated = `${BEGIN}\n${blocks.join('\n')}\n${END}`;
const existing = css.includes(BEGIN)
  ? css.slice(css.indexOf(BEGIN), css.indexOf(END) + END.length)
  : null;

if (process.argv.includes('--check')) {
  if (existing === generated) { console.log('THEMES=CURRENT'); process.exit(0); }
  console.error('THEMES=STALE — run `node tools/generate-themes.mjs`');
  process.exit(1);
}
const next = existing ? css.replace(existing, generated) : `${css}\n\n${generated}\n`;
writeFileSync(CSS, next);
console.log(`THEMES_WRITTEN=${THEMES.length - 1} blocks (plus the default, which has none)`);
console.log(`TOKENS_PER_THEME=${[...buildTheme(THEMES[7], tokens).keys()].length} for daylight`);
